print("Enter one noun:")
noun=str(input())
print("Enter an adjective:")
adjective=str(input())
print("Enter a different nown:")
nounTwo=str(input())
print("The",noun,"jumped over the",adjective,nounTwo".\n")
